project:
  name: Payment cards api
  debug: true
  environment: development
  serviceName: pay-cards-service

grpc:
  host: 0.0.0.0
  port: 8082
  maxConnectionIdle: 5 # Minutes
  timeout: 15 # Seconds
  maxConnectionAge: 5 # Minutes

telemetry:
  graylogPath: 127.0.0.1:12201

rest:
  host: 0.0.0.0
  port: 8080

metrics:
  host: 0.0.0.0
  port: 9100
  path: /metrics

jaeger:
  service: "pay-card-api"
  host: "0.0.0.0"
  port: ":6831"

status:
  host: 0.0.0.0
  port: 8000
  livenessPath: /live
  readinessPath: /ready
  versionPath: /version

database:
  host: localhost
  port: 5432
  user: docker
  password: docker
  name: pay_card_api
  sslmode: disable
  driver: pgx

retranslator:
  channelSize: 512
  consumerCount: 2
  consumeSize: 10
  consumeTimeout: 1000
  producerCount: 2
  workerCount: 2

kafka:
  capacity: 512
  topic: "omp-template-events"
  groupId: "pay-card-api"
  brokers:
    - "kafka:9092"
    - "localhost:9094"
